### ISSUE TITLE
Inclusion in F-Droid

### ISSUE THREAD

**Issue by renatocan** [iiordanov/remote-desktop-clients#148] opened 2018-12-04 11:11 UTC
Hi,

Great app! I think it should be included in [F-Droid](https://f-droid.org/) repo. I can submit it but I need your consent. Is it ok for me to submit the app?

Thanks,

Renato.

**Comment by colbycdev** [comment] 2019-02-19 16:30
The free version is in f Droid. This issue should be closed

**Comment by DJCrashdummy** [comment] 2019-04-10 17:20
@alexa-v2 no, it is unfortunately not!

...but this issue is a duplicate of #70.

**Comment by iiordanov** [comment] 2020-04-19 22:38
Closed since it's a duplicate.

**Closed** 2020-04-19 22:38 UTC
