### ISSUE TITLE
Dragging stop mouse on touchpad mode

### ISSUE THREAD

**Issue by Ghplayer2000** [iiordanov/remote-desktop-clients#388] opened 2022-08-17 02:51 UTC
When i try to drag in touchpad mode, the mouse cannot be moved until i stop dragging.

**Comment by Ghplayer2000** [comment] 2022-08-17 13:58
Version 5.1.0_115108 (Free Version)

**Comment by remcolam** [comment] 2022-08-17 17:26
I will give a +1 on this. I have the same issue, both on tablet (android 12) and phone (android 13 (pixel 5)). Same version on both (5.1.0_115108)

**Comment by iiordanov** [comment] 2022-08-19 05:06
The issue is fixed in v5.1.1. Thanks for reporting!

**Closed by iiordanov** 2022-08-19 05:06 UTC
