### ISSUE TITLE
aSpice -  Single or double clicking a mouse is not reliable.

### ISSUE THREAD

**Issue by birdra73** [iiordanov/remote-desktop-clients#394] opened 2022-11-19 16:41 UTC
Slightly unusual behaviour - e.g. a click doesn't take, or mistakenly forces a drag of icon and won't unselect. Doesn't occur when accessing the same vm with bVNC.

**Comment by iiordanov** [comment] 2022-12-19 00:14
Hey,

I cannot reproduce this with my Pixel 7 and test VMs. I tried Ubuntu 20.04 and Windows 10. I think i'll need some more details to try to reproduce this. Could you tell me more about your environment and your device as well?

Thanks!

**Comment by birdra73** [comment] 2022-12-20 20:26
Hey, sure.

The VM is a fresh install of Lubuntu 22.04, running on an up to date Unraid server 6.11.1

My Android device is an unmodified (i.e. stock) Lenovo Tab P11 pro TB-J706L. The device has a Lenovo detachable keyboard with mouse pad that comes with the tablet.

aSpice is your latest.

I just tested again and narrowed the problem down - the behaviour of depressing the mousepad (rather than just tapping the mousepad) is strangely configured and this causes all the problems.
[Note: bvnc has standard correct behaviour for the same VM]

1. Depressing the mouse pad once should select an item, as in bVNC - it does not. Rather it seems to create a starting point lock which
- makes the highlighted object get dragged around the screen with no obvious way of releasing
- creates a starting point for text highlighting, again with no obvious way of releasing.
2. Holding the press should allow you to select until the press is released, as in bVNC - it does not.
3. If the mousepad has been depressed then any normal taps or screen taps will not work.

I note that when using the screen only, since selection cannot be done in this way, the behaviour is reasonable.

Hope this is helpful - thanks for your attention on this.


19 Dec 2022 02:14:57 iiordanov ***@***.***>:

**Comment by iiordanov** [comment] 2023-01-01 18:06
Fixed in https://github.com/iiordanov/remote-desktop-clients/commit/c230e6234159f813add56a52f2053b4cb3079fc4. Will be in Beta shortly.

**Closed by iiordanov** 2023-01-01 18:06 UTC
Labels: bug
